# Generated by Django 4.2.2 on 2023-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(default=678342678432),
        ),
        migrations.AddField(
            model_name='book',
            name='quantiy',
            field=models.IntegerField(default=1),
        ),
    ]
